name: Database Creation for all API & UI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual run
    inputs:
        logLevel:
          description: 'Environment where Database Needs to be created'
          required: true
          default: 'test'
          type: choice
          options:
            - dev
            - test
            - prod
        postgres_database:
          description: 'Enter Database Name'
          required: true
          type: string            
        postgres_db_user:
          description: 'Enter UserName'
          required: true
          type: string
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true

jobs:
    automate-tasks:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.x

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install psycopg2-binary

        - name : Run script to create database and user
          run: python automate_tasks.py    
        
        - name : Set env
          env: 
              POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
              POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
              POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} 
              POSTGRES_DBUSER_PASSWORD : ${{ secrets.POSTGRES_PASSWORD }}
              POSTGRES_DATABASE: ${{ inputs.postgres_database }} 
              POSTGRES_DB_USER: ${{ inputs.postgres_db_user }} 
          run: echo "Hello world"
